badge: "&6[TreeboTrunks]&r"
checkUpdates: true
updateChecker: spigot
bstatsIntegration: true
whitelistBlocks:
  - AIR
  - GRASS
  - DEAD_BUSH
  - FERN
  - LARGE_FERN
  - TALL_GRASS
  - DANDELION
  - POPPY