name: TreeboTrunks
version: ${project.version}
main: me.shakeforprotein.treebotrunks.TreeboTrunk
api-version: 1.13
authors: [ShakeforProtein]
description: Mass virtual chest storage
website: http://treebomc.com

commands:
  belt:
    permission: treebotrunk.belt.open
    usage: "/barrel [number] - Opens a virtual belt. If a number is specified, it will attempt to open a belt with that identifier."
  barrel:
    permission: treebotrunk.barrel.open
    usage: "/barrel [number] - Opens a virtual barrel. If a number is specified, it will attempt to open a barrel with that identifier."
  chest:
    permission: treebotrunk.chest.open
    usage: "/chest [number] - Opens a virtual double chest. If a number is specified, it will attempt to open a chest with that identifier."
  trash:
    permission: treebotrunk.trash.open
    usage: "/trash - Opens an inventory that will eat items"
  addtrunk:
    permission: treebotrunk.admin
    usage: "/addtrunk <Player> <type> <number>"
  anvil:
    permission: treebotrunk.anvil
    usage: "/anvil"
    description: "Temporarily Places an Anvil at your feet if the block is clear"
  craft:
    permission: treebotrunk.craft
    usage: "/craft"
    description: "Opens a virtual crafting table"
  enchant:
    permission: treebotrunk.enchant
    usage: "/enchant"
    description: "Temporarily Places an Anvil at your feet if the block is clear"
  grindstone:
    permission: treebotrunk.grindstone
    usage: "/grindstone"
    description: "Temporarily Places an grindstone at your feet if the block is clear"
  stonecutter:
    permission: treebotrunk.stonecutter
    usage: "/stonecutter"
    description: "Temporarily Places an stonecutter at your feet if the block is clear"

permissions:
  treebotrunk.belt.open:
    default: false
    description: Allows opening of TreeBelts
  treebotrunk.chest.open:
    default: false
    description: Allows opening of TreeboChests
  treebotrunk.barrel.open:
    default: false
    description: Allows opening of TreeBarrels
  treebotrunk.trash.open:
    default: true
    description: Allows opening of TreeBin
  treebotrunk.anvil:
    default: op
  treebotrunk.craft:
    default: op
  treebotrunk.enchant:
    default: op
  treebotrunk.grindstone:
    default: op
  treebotrunk.stonecutter:
    default: op