name: TreeboTrunks
version: ${project.version}
main: me.shakeforprotein.treebotrunks.TreeboTrunk
api-version: 1.13
authors: [ShakeforProtein]
description: Mass virtual chest storage
website: http://treebomc.com
softdepend: [WorldGuard, WorldEdit]

commands:
  belt:
    permission: treebotrunk.belt.open
    usage: "/barrel [number] - Opens a virtual belt. If a number is specified, it will attempt to open a belt with that identifier."
  barrel:
    permission: treebotrunk.barrel.open
    usage: "/barrel [number] - Opens a virtual barrel. If a number is specified, it will attempt to open a barrel with that identifier."
  chest:
    permission: treebotrunk.chest.open
    usage: "/chest [number] - Opens a virtual double chest. If a number is specified, it will attempt to open a chest with that identifier."
  trash:
    permission: treebotrunk.trash.open
    usage: "/trash - Opens an inventory that will eat items"
  addtrunk:
    permission: treebotrunk.admin
    usage: "/addtrunk <Player> <type> <number>"
  anvil:
    permission: treebotrunk.anvil
    usage: "/anvil"
    description: "Temporarily Places an Anvil at your feet if the block is clear"
  craft:
    permission: treebotrunk.craft
    usage: "/craft"
    description: "Opens a virtual crafting table"
  enchant:
    permission: treebotrunk.enchant
    usage: "/enchant"
    description: "Temporarily Places an Anvil at your feet if the block is clear"
  grindstone:
    permission: treebotrunk.grindstone
    usage: "/grindstone"
    description: "Temporarily Places an grindstone at your feet if the block is clear"
  stonecutter:
    permission: treebotrunk.stonecutter
    usage: "/stonecutter"
    description: "Temporarily Places an stonecutter at your feet if the block is clear"
  cartographer:
    permission: treebotrunk.cartographer
    usage: "/cartographer"
    description: "Temporarily Places a cartography table at your feet if the block is clear"
  loom:
    permission: treebotrunk.loom
    usage: "/loom"
    description: "Temporarily Places a loom at your feet if the block is clear"
  furnace:
    permission: treebotrunk.furnace
    usage: "/furnace"
  furnace2:
    permission: treebotrunk.furnace
    usage: "/furnace2"
    description: "Temporarily Places a Furnace at your feet if the block is clear"
  blastfurnace:
    permission: treebotrunk.blastfurnace
    usage: "/blastfurnace"
    description: "Temporarily Places a Blast Furnace at your feet if the block is clear"
  smoker:
    permission: treebotrunk.smoker
    usage: "/smoker"
    description: "Temporarily Places a Smoker at your feet if the block is clear"
  brew:
    permission: treebotrunk.brew
    usage: "/brew"
    description: "Temporarily Places a Brewing Stand at your feet if the block is clear"
  chests:
    permission: treebotrunk.chest.open
  belts:
    permission: treebotrunk.belt.open
  barrels:
    permission: treebotrunk.barrel.open
permissions:
  treebotrunks.admin:
    default: op
    description: Allows player to see update notifications
  treebotrunk.belt.open:
    default: false
    description: Allows opening of TreeBelts
  treebotrunk.chest.open:
    default: false
    description: Allows opening of TreeboChests
  treebotrunk.barrel.open:
    default: false
    description: Allows opening of TreeBarrels
  treebotrunk.trash.open:
    default: true
    description: Allows opening of TreeBin
  treebotrunk.anvil:
    default: op
  treebotrunk.craft:
    default: op
  treebotrunk.enchant:
    default: op
  treebotrunk.grindstone:
    default: op
  treebotrunk.stonecutter:
    default: op
  treebotrunk.cartographer:
    default: op
  treebotrunk.loom:
    default: op
  treebotrunk.furnace:
    default: op
  treebotrunk.blastfurnace:
    default: op
  treebotrunk.brew:
    default: op
  treebotrunk.smoker:
    default: op